create table if not exists public.hao_r9_okooo_shadow_runs_v01 (
  id bigint generated by default as identity primary key,
  issue_no text not null,
  captured_at timestamptz not null default now(),
  rule_version text not null default 'HC24-R9-OKOOO-HJ38-v0.1',
  fixture_source text,
  status text not null,
  total_matches integer not null default 14,
  confirmed_matches integer not null default 0,
  hj38_overlap integer not null default 0,
  okooo_verified integer not null default 0,
  retained_9 jsonb not null default '[]'::jsonb,
  discarded_5 jsonb not null default '[]'::jsonb,
  ticket_310 jsonb,
  combination_count integer,
  cost_rmb integer,
  ticket_status text,
  base_model_revision_id bigint,
  summary jsonb not null default '{}'::jsonb
);

create table if not exists public.hao_r9_okooo_shadow_v01 (
  id bigint generated by default as identity primary key,
  shadow_run_id bigint not null references public.hao_r9_okooo_shadow_runs_v01(id) on delete cascade,
  issue_no text not null,
  seq_no integer not null check (seq_no between 1 and 14),
  competition text,
  home_team text not null,
  away_team text not null,
  kickoff_at timestamptz,
  top1 text,
  second_pick text,
  p_home numeric,
  p_draw numeric,
  p_away numeric,
  confidence_label text,
  dq text,
  hur text,
  dtr text,
  dlr text,
  base_source text,
  hj38_prediction_id bigint,
  hj38_upset jsonb,
  okooo_match_id text,
  okooo_source_url text,
  exchange_scale text,
  transaction_rows jsonb,
  index_rows jsonb,
  market_top1 text,
  market_top1_prob numeric,
  behavior_top1 text,
  behavior_strength text,
  popularity_gap numeric,
  top_heat numeric,
  top_profit_index numeric,
  fund_anomaly boolean not null default false,
  popularity_divergence boolean not null default false,
  cold_score integer not null default 0,
  cold_level text not null default '低',
  cold_reasons text[] not null default '{}',
  keep_rank integer,
  kept_in_9 boolean,
  ticket_role text,
  ticket_pick text,
  coverage_probability numeric,
  source_payload jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now(),
  unique(shadow_run_id, seq_no)
);

create index if not exists hao_r9_okooo_shadow_runs_issue_idx
  on public.hao_r9_okooo_shadow_runs_v01(issue_no, captured_at desc);
create index if not exists hao_r9_okooo_shadow_issue_seq_idx
  on public.hao_r9_okooo_shadow_v01(issue_no, seq_no, captured_at desc);
create index if not exists hao_r9_okooo_shadow_run_rank_idx
  on public.hao_r9_okooo_shadow_v01(shadow_run_id, keep_rank);

alter table public.hao_r9_okooo_shadow_runs_v01 enable row level security;
alter table public.hao_r9_okooo_shadow_v01 enable row level security;

revoke all on table public.hao_r9_okooo_shadow_runs_v01 from anon, authenticated;
revoke all on table public.hao_r9_okooo_shadow_v01 from anon, authenticated;
grant select,insert,update,delete on table public.hao_r9_okooo_shadow_runs_v01 to service_role;
grant select,insert,update,delete on table public.hao_r9_okooo_shadow_v01 to service_role;
grant usage,select on sequence public.hao_r9_okooo_shadow_runs_v01_id_seq to service_role;
grant usage,select on sequence public.hao_r9_okooo_shadow_v01_id_seq to service_role;
