create table if not exists public.soren_admin_password_reset_audit_v1 (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete restrict,
  target_user_id uuid not null references auth.users(id) on delete restrict,
  target_email text not null,
  created_at timestamptz not null default now()
);

alter table public.soren_admin_password_reset_audit_v1 enable row level security;

revoke all on table public.soren_admin_password_reset_audit_v1 from anon, authenticated;
revoke all on sequence public.soren_admin_password_reset_audit_v1_id_seq from anon, authenticated;

comment on table public.soren_admin_password_reset_audit_v1 is
'Administrator password-reset audit log. Never stores passwords or password hashes.';
