create table if not exists public.soren_r9_shadow_runs_v1 (
  id bigint generated by default as identity primary key,
  issue_no text not null,
  model_version text not null,
  captured_at timestamptz not null default now(),
  source_url text not null,
  sale_cutoff_at timestamptz null,
  status text not null,
  pool jsonb not null,
  selection jsonb not null,
  diagnostics jsonb not null default '{}'::jsonb,
  no_result_leakage boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.soren_r9_shadow_runs_v1 enable row level security;

revoke all on table public.soren_r9_shadow_runs_v1 from anon, authenticated;
grant select, insert, update, delete on table public.soren_r9_shadow_runs_v1 to service_role;
grant usage, select on sequence public.soren_r9_shadow_runs_v1_id_seq to service_role;

create index if not exists soren_r9_shadow_runs_v1_issue_captured_idx
  on public.soren_r9_shadow_runs_v1(issue_no, captured_at desc);
